# Generated by Django 4.2.20 on 2025-04-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonology',
            new_name='technology',
        ),
    ]
